/*
 * File: ADRBasicViewer.ui.js
 * Date: Sun Mar 06 2011 14:13:54 GMT-0400 (AST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ADRBasicViewerUi = Ext.extend(Ext.TabPanel, {
    activeTab: 2,
    width: 960,
    height: 600,
    title: '',
    initComponent: function() {
        this.tpl = [
            '\'<tpl for=".">\',',
            '            \'<div class="thumb-wrap" id="{name}">\',',
            '            \'<div class="thumb"><img src="{url}" title="{name}"></div>\',',
            '            \'<span class="x-editable">{shortName}</span></div>\',',
            '        </tpl>\',',
            '        \'<div class="x-clear"></div>'
        ];
        this.items = [
            {
                xtype: 'panel',
                title: 'Overview',
                width: 426,
                height: 800,
                layout: 'hbox',
                border: false,
                items: [
                    {
                        flex: 1,
                        xtype: 'descriptionpanel'
                    },
                    {
                        flex: 1,
                        xtype: 'filespanel'
                    }
                ]
            },
            {
                xtype: 'viewerpanel'
            },
            {
                xtype: 'managepanel'
            }
        ];
        ADRBasicViewerUi.superclass.initComponent.call(this);
    }
});
