/*
 * File: DescriptionPanel.js
 * Date: Sun Mar 06 2011 14:13:54 GMT-0400 (AST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

DescriptionPanel = Ext.extend(DescriptionPanelUi, {
    initComponent: function() {
        DescriptionPanel.superclass.initComponent.call(this);
    }
});
Ext.reg('descriptionpanel', DescriptionPanel);