/*
 * File: DescriptionPanel.ui.js
 * Date: Sun Mar 06 2011 14:13:54 GMT-0400 (AST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

DescriptionPanelUi = Ext.extend(Ext.Panel, {
    title: 'Description',
    width: 400,
    height: 250,
    initComponent: function() {
        this.items = [
            {
                xtype: 'dataview',
                width: 400,
                height: 250,
                itemSelector: 'div',
                store: 'description',
                tpl: '<tpl for="."><div>Template</div></tpl>'
            }
        ];
        DescriptionPanelUi.superclass.initComponent.call(this);
    }
});
