/*
 * File: DescriptionPanel.ui.js
 * Date: Mon Mar 07 2011 04:09:17 GMT-0600 (CST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

DescriptionPanelUi = Ext.extend(Ext.Panel, {
    title: 'Description',
    initComponent: function() {
        DescriptionPanelUi.superclass.initComponent.call(this);
    }
});
