/*
 * File: ManagePanel.ui.js
 * Date: Sun Mar 06 2011 14:13:54 GMT-0400 (AST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ManagePanelUi = Ext.extend(Ext.Panel, {
    title: 'Manage',
    width: 960,
    height: 700,
    layout: 'vbox',
    initComponent: function() {
        this.layoutConfig = {
            padding: '5 5 5 5',
            align: 'stretch',
            defaultMargins: {
                top: 4,
                left: 2,
                right: 2,
                bottom: 4
            }
        };
        this.items = [
            {
                xtype: 'form',
                title: 'Edit Object',
                height: 120,
                padding: 12,
                flex: 1,
                items: [
                    {
                        xtype: 'compositefield',
                        fieldLabel: 'Status',
                        anchor: '100%',
                        items: [
                            {
                                xtype: 'radio',
                                boxLabel: 'Published',
                                inputValue: 0,
                                name: 'status',
                                flex: 1
                            },
                            {
                                xtype: 'radio',
                                boxLabel: 'Unpublished',
                                name: 'status',
                                flex: 1
                            }
                        ]
                    },
                    {
                        xtype: 'spacer',
                        height: 10
                    },
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        layoutConfig: {
                            pack: 'end',
                            defaultMargins: {
                                top: 4,
                                left: 4,
                                bottom: 4,
                                right: 4
                            }
                        },
                        items: [
                            {
                                xtype: 'button',
                                text: 'Edit',
                                scale: 'medium',
                                width: 100
                            },
                            {
                                xtype: 'button',
                                text: 'Delete',
                                scale: 'medium',
                                width: 100
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'form',
                title: 'Edit Description',
                padding: 10,
                flex: 1,
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Title',
                        anchor: '100%',
                        name: 'title'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Author',
                        anchor: '100%',
                        name: 'author'
                    },
                    {
                        xtype: 'textarea',
                        anchor: '100%',
                        fieldLabel: 'Description',
                        name: 'description',
                        height: 123
                    },
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        defaults: '{align: right}',
                        hideBorders: true,
                        layoutConfig: {
                            padding: '4 4 4 4',
                            defaultMargins: '{top: 2, left: 2 right: 2, bottom: 2}',
                            pack: 'end'
                        },
                        items: [
                            {
                                xtype: 'button',
                                text: 'Save',
                                iconAlign: 'right',
                                width: 100,
                                scale: 'medium',
                                tooltipType: 'title',
                                tooltip: 'Save Changes',
                                flex: 1
                            },
                            {
                                xtype: 'button',
                                text: 'Reset',
                                width: 100,
                                iconAlign: 'right',
                                minWidth: 100,
                                scale: 'medium',
                                flex: 1
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'form',
                title: 'Manage Files',
                padding: 10,
                flex: 1,
                items: [
                    {
                        xtype: 'dataview',
                        itemSelector: 'div',
                        store: 'datastreams',
                        tpl: '<tpl for="."><div>Template</div></tpl>'
                    }
                ]
            }
        ];
        ManagePanelUi.superclass.initComponent.call(this);
    }
});
