/*
 * File: ViewerPanel.ui.js
 * Date: Sun Mar 06 2011 14:13:54 GMT-0400 (AST)
 * 
 * This file was generated by Ext Designer version xds-1.0.3.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ViewerPanelUi = Ext.extend(Ext.Panel, {
    title: 'Viewer',
    width: 400,
    height: 250,
    initComponent: function() {
        ViewerPanelUi.superclass.initComponent.call(this);
    }
});
